name: Digger Workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]
  issue_comment:
    types: [created]

jobs:
  digger-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare local backend state dir
        run: mkdir -p envs/test/.terraform-state

      - name: Cache local Terraform state (test only)
        uses: actions/cache@v4
        with:
          path: |
            envs/**/.terraform-state
          key: terraform-state-${{ github.repository }}-${{ github.ref_name }}
          restore-keys: |
            terraform-state-${{ github.repository }}-

      - name: Run Digger (PR/CommentOps)
        uses: diggerhq/digger@vLatest
        with:
          # digger-spec: ${{ inputs.spec }}
          # digger-token: ${{ secrets.DIGGER_TOKEN }}
          # digger-hostname: https://otaco.app
          no-backend: true
          setup-terraform: true
          terraform-version: 1.5.7
          disable-locking: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ github.token }}
